name: create_base
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  auto_route:
  cupertino_icons: 
  equatable:
  flutter:
    sdk: flutter
  flutter_bloc: 
  freezed:
  freezed_annotation:
  get_it:
  http: 
  injectable:


dev_dependencies:
  auto_route_generator: ^3.0.1
  build_runner:
  flutter_lints:
  injectable_generator:

flutter:
  uses-material-design: true
