name: create_base
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: 
  freezed:
  freezed_annotation:
  get_it:
  http: 
  injectable:


dev_dependencies:
  build_runner: ^2.1.4
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  injectable_generator: ^1.5.2  

flutter:
  uses-material-design: true
